export const questionArr = [
    {
      id: 1,
      title: "성별은 무엇입니까?",
      answerList: ["남자", "여자"],
      answer: { me: "", you: "" },
    },
    {
      id: 2,
      title: "당신의 연령대는 무엇입니까?",
      answerList: ["10-20", "20-30", "30-40", "40-50", "50 이상"],
      answer: { me: "", you: "" },
    },
    {
      id: 3,
      title: "다른 사람들의 감정을 쉽게 이해하고 공감하는 편이다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 4,
      title: "새로운 사람들과 쉽게 친해진다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 5,
      title: "변화에 대해 열린 마음을 갖고 있다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 6,
      title: "일 외의 운동과 문화에 관심이 많다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 7,
      title: "결정을 내리기 전에 꼼꼼히 검토하는 편이다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 8,
      title: "스트레스를 잘 감당하는 편이다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 9,
      title: "새로운 도전을 즐기는 편이다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 10,
      title: "감정을 솔직하게 표현하는 편이다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 11,
      title: "타인과의 갈등 상황을 잘 해결하는 편이다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 12,
      title: "책임감이 강하고 신뢰성이 높다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 13,
      title: "상대방과의 관계회복이나 발전을 위해 먼저 제안하는 편이다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
    {
      id: 14,
      title: "상대방에게 사랑받고 있다고 느낀다",
      answerList: ["O", "X"],
      answer: { me: "", you: "" },
    },
  ];